### ISSUE TITLE
X position incorrect in one of the rounded ends

### ISSUE THREAD

**Issue by NSCabezon** [danielamitay/DACircularProgress#29]
One of the rounded ends, the x position is incorrect, i guess it starts from absolute X and the view from the center, that causes this to happen

![captura de pantalla 2014-06-20 a la s 11 38 23](https://cloud.githubusercontent.com/assets/563761/3338647/a6baf7ec-f85e-11e3-9556-b7cc2ea1134e.png)

**Comment by SirupGuy** [comment]
This happens when the width of the view is different than the height of the view.
