### ISSUE TITLE
track tint colour does not work on iPad air.

### ISSUE THREAD

**Issue by ManjitBedi** [danielamitay/DACircularProgress#35]
This is quite strange.  I cannot set the track tint colour when running the app on an iPad air.  To get it to work, I renamed the property in the class.

**Comment by BasheerSience** [comment]
@ManjitBedi does it work now after renaming ?

**Comment by ManjitBedi** [comment]
Hi.

It has been so long since I encountered the issue;  I don’t recall what I did precisely to get it to work.

Manjit

**Comment by BasheerSience** [comment]
thanks, I had to remove one line in initialize to make it work :)
