### ISSUE TITLE
Warning in Xcode 6.3 beta

### ISSUE THREAD

**Issue by sticksen** [danielamitay/DACircularProgress#44]
![screen shot 2015-02-10 at 12 29 36](https://cloud.githubusercontent.com/assets/2657113/6126399/8f392ac8-b120-11e4-8c29-aff289373a80.png)
![screen shot 2015-02-10 at 12 29 12](https://cloud.githubusercontent.com/assets/2657113/6126400/91960d86-b120-11e4-89d0-5d48491a8164.png)

**Comment by nilshott** [comment]
This issue is still present in Xcode 6.3 final. Can be fixed as suggested.

**Comment by danielamitay** [comment]
Should be resolved by #49 

Version 2.3.1 contains the fix
