### ISSUE TITLE
trackTintColor and progressTintColor does not work on table cell

### ISSUE THREAD

**Issue by cssmhyl** [danielamitay/DACircularProgress#51]
I customize a table cell and put the circular progress on the cell, then I set the trackTintColor, progressTintColor and the roundedCorners, but all these doesn't work,the circular progress's progressTintColor still is white,  I don't know why.

**Comment by cssmhyl** [comment]
I creat the cell with xib and set color in awakeFromNib

**Comment by danielamitay** [comment]
Would you be able to provide a simple example application replicating the issue?

**Comment by vanderneut** [comment]
FWIW: I am using DACircularProgress in custom table cells coming from a nib and I have no problem setting the `trackTintColor` and `progressTintColor` properties. In fact, I'm using different colors in different rows of the same table and it works perfectly. 

In my code I am setting the colors in the `-tableView:cellForRowAtIndexPath:` UITableView delegate method.

Erik

**Comment by cssmhyl** [comment]
The sample project is:
https://github.com/cssmhyl/TestForCircularProgress

The bug only appears on iOS7.(iOS8 is ok)
![circalur_iphone5_ios8](https://cloud.githubu
![circalur_iphone4s_ios7](https://cloud.githubusercontent.com/assets/6084247/7488886/c7051816-f402-11e4-8ce6-2a12de2b32f2.PNG)
sercontent.com/assets/6084247/7488884/bcb5de68-f402-11e4-9cd7-d1ab9aa3b44f.png)

**Comment by cuongtv51** [comment]
Hi cssmhyl,
