### ISSUE TITLE
Could make it look like ProgressHUD

### ISSUE THREAD

**Issue by diegothucao** [danielamitay/DACircularProgress#56]
Could make it easier to user like ProgressHUD. Show it can show default in center then users can not touch any areas else....
And easy to call the method like show and hide...

**Comment by danielamitay** [comment]
Unfortunately I think that this sort of functionality would be out of the scope of the intention of DACircularProgress. The idea was to provide a simple class such as UIActivityIndicatorView. It is my feeling that other projects such as [MBProgressHUD](https://github.com/jdg/MBProgressHUD) better address the need for HUD, and building one into DACircularProgress would only add unneeded complexity.
